package com.david.java.demo.lonsec;

public interface Constant {
	
	String CONFIG="config";
	String DEFAULT_FILENAME="config.prop";
	String EXCESS_RULE="EXCESS_RULE";
	String OUT_PERFORMED_LABEL="OUT_PERFORMED_LABEL";
	String UNDER_PERFORMED_LABEL="UNDER_PERFORMED_LABEL";
	String FUNDS_FILEPATH="FUNDS_FILEPATH";
	String BENCHMARK_FILEPATH="BENCHMARK_FILEPATH";
	String FUND_RETURN_SERIES_FILEPATH="FUND_RETURN_SERIES_FILEPATH";
	String BENCH_RETURN_SERIES_FILEPATH="BENCH_RETURN_SERIES_FILEPATH";
	String MONTHLY_OUTPERFORMANCE_FILEPATH="MONTHLY_OUTPERFORMANCE_FILEPATH";
	String DATE_FORMAT="DATE_FORMAT";
	

}
